### ISSUE TITLE
Feature request:  on the 'Reverse Engineer' window, remember the settings specific to every connection

### ISSUE THREAD

**Issue by venetasoft** [ErikFrits/EF-Tools#10]
On data import projects, it is common to have multiple connections to multiple SQL Server databases.
Every time we run the (awesome, thank you!!!) EF Tools to rebuild the models from one of the dbs, we have to modify all the settings in the 'Generate EF Core Model' window by hand every time (as it remembers only the last one).
It would be awesome if the UI would "remember" those settings for every connection (dbcontext) in the project.

Thank you.

**Comment by ErikFrits** [comment]
Hi @venetasoft , I think there is some miscommunication.

I haven't made any tools for databases and I have no idea what is "Generate EF Core Model". After googling I think it comes from Entity Framework Core (EF Core), Which is unrelated to my EF-Tools extension. 

EF-Tools is a python extension made for Autodesk Revit application.

**Comment by venetasoft** [comment]
Sorry....Wrong place :)
