### ISSUE TITLE
ViewFilters: Copy to Another View

### ISSUE THREAD

**Issue by MartinCayrus** [ErikFrits/EF-Tools#11]
Hi,
your copy View Filter add-in came in handy but I also needed it to copy the Visibility Filter sometimes so I added 2 lines of code to also copy the Boolean:

visibility = self.src_view.GetFilterVisibility(filter.Id)
                 view.SetFilterVisibility(filter.Id, visibility)

Thanks and hopefully this contributes a little :)

**Comment by Konrad-X-PLAN** [comment]
Is it fixed? 
It is not working for me.

**Comment by amagr0** [comment]
I would also like to be able to select the "Visibility" state of the filter.
I couldn't find a way to do it — is it already implemented?
Thanks!

**Comment by MazzA999** [comment]
One question: which line of the _script.py_ file I add for make this function available??

**Comment by amagr0** [comment]
I would also like to know where to add these lines in the script.
Thanks
