### ISSUE TITLE
Replace Materials doesn't work in 23

### ISSUE THREAD

**Issue by LivingstonerVillain** [ErikFrits/EF-Tools#13]
Hi Erik, stumbled across your Youtube vid about replacing materials. Could be a life saver but it doesn't work. Tested n multiple projects in Revit 2023 but I only get this log "In Total: Material was replaced in 0 Parameters.". Hope you can fix it! Best of luck.

**Comment by ErikFrits** [comment]
Sorry haven't seen this issue.

I recently used it as well, and it works, but reporting feature is broken.
So it will always tell you Materials were replaced in 0 parameters, but in reality it actually replaces found matches.

I will check what's going on soon.

**Comment by ErikFrits** [comment]
✅ I fixed the issue.

For some reason my count was set to 0 right before printing to the console... 
No idea how it got there
