### ISSUE TITLE
EF tools ERROR message installing . Not able to connect with server

### ISSUE THREAD

**Issue by MANYAL77** [ErikFrits/EF-Tools#16]
Hi Eric, trying to install EF extension with PyRevit version 4.8.13 in Revit 2024 I am getting this error message. Would appreciate any help. Thank you

pd. I am tryuing to attached jpg image file and not sure if I am allowed to. Sorry, let me know if there is any other way of sending or contacting with you

**Comment by ErikFrits** [comment]
Hi Manyal,

You haven't attached any screenshots.

Usually the biggest issue to install EF-Tools is because of Firewall protection in the company.
But if you can provide me the error message, I might tell you more about it.
