### ISSUE TITLE
EF_Tools: Walls - Disallow Join

### ISSUE THREAD

**Issue by eccappuccino** [ErikFrits/EF-Tools#20]
Hi there, 

Not sure why the Disallow Join function for Walls have stopped working and comes up with this message. 

![240718_EF-Tools_DisallowJoin](https://github.com/user-attachments/assets/1c8ec555-23c2-4119-896c-5f17e12aa6c0)

Already re-installed the EF_Tools extension, but did not help. 
The other functions are working fine though. 
Something missing from my installation?

Thank you.

**Comment by ErikFrits** [comment]
Hi,
This is my mistake.

I assume you run it on Revit 2021.
There are some changes in API between Revit 2021 and 2022+. 

I will check

**Comment by ErikFrits** [comment]
Should be fixed now.

**Comment by eccappuccino** [comment]
Hi, 
I am using Revit 2022 and 2024. 
But it works fine now, thank you so much!
