### ISSUE TITLE
Can not install EF Tools

### ISSUE THREAD

**Issue by MariusPostolachi** [ErikFrits/EF-Tools#21]
Hi all,

I am not able to install EF Tools on Revit 2023.
When I try to install it, I get this error.
Can you please support me?

Thank you!
![image](https://github.com/user-attachments/assets/f2cc8687-7fe4-4247-84fa-6693af98e685)

**Comment by ErikFrits** [comment]
Hi,
People get this kind of error message when you have firewall/anti-virus protection blocking the connection to GitHub to download the package. It's quite standard to block any outside connections in big companies, but you can talk to IT department about that to see how to bypass that.

Enjoy the tools!
