### ISSUE TITLE
Lines in the tooltip are too long

### ISSUE THREAD

**Issue by Thomas84** [ErikFrits/EF-Tools#4]
![image](https://user-images.githubusercontent.com/5624034/143837628-86cd6662-7170-4738-82e7-b2804a54e8b9.png)

**Comment by ErikFrits** [comment]
Thanks for letting me know @Thomas84 
What resolution are you using on your PC/Laptop? I have it exactly at the end on both my PC and Laptop.

**Comment by Thomas84** [comment]
2560x1440
