### ISSUE TITLE
Feature Request: Align View Title?

### ISSUE THREAD

**Issue by kpfanny** [ErikFrits/EF-Tools#5]
Hello! Been loving the features in this toolbar ever since it was rolled out with the latest version of pyRevit! I do have a feature request, though:

Could the "Align Viewports" tool have an option to align the locations of the View Title in addition to the viewports? Not sure how difficult or feasible it is to obtain and set the location of the view title through the API, but this would be very helpful.

Thank you!

**Comment by ErikFrits** [comment]
Hi kpfanny,
Thank you, I appreciate it.

I have tried to make such a tool a long time ago that would align View Titles, and at the time I have failed. There was a workaround to code it but it was not a quick fix.

At the moment I have many other tools in mind that I want to finish before I would try to add more features to that one. 
I will keep it in mind and see what I can do, but can't promise you this feature any time soon. 

Sorry, I can barely find enough spare time nowadays.
😓
