### ISSUE TITLE
Regions : Change Linestyle not working

### ISSUE THREAD

**Issue by dsellam** [ErikFrits/EF-Tools#9]
Regions : Change Linestyle seems to not working on my computer.
the window for chosing linestyle Opens but nothing happens after validating the desired linestyle.

Revit 2022.1 French
Regions : Change Linestyle V1.2

**Comment by ErikFrits** [comment]
Thank you for reporting the issue Daniel!
I will have a look at it!

**Comment by ErikFrits** [comment]
🐛 Bug is solved! Update EF-Tools to get V1.3 of this tool

I guess I broke it last time when I was making changes to GUI...
